spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/grabcontent?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        show_sql: true
  liquibase:
    change-log: classpath:/liquibase/liquibase-master.xml

application:
  cartoonList:
    - name: Dr-Stone
      url: http://www.niceoppai.net/Dr-Stone/
